### PR TITLE
Add Unix socket support

### PR DESCRIPTION
**Pull request by davidmartos96**
While testing the package I noticed the Unix socket option was missing. This seems to work great.
Thank you for this package!

### CODE REVIEW

**Comment by isoos** [comment]
@davidmartos96: could you also bump the version and add an entry in the changelog?

**Comment by davidmartos96** [comment]
@isoos Done!

**Comment by isoos** [comment]
I've added another commit with the parsing + other methods that I think are important. Please let me know if it looks ok to you, then I'll merge and publish...

**Comment by davidmartos96** [comment]
@isoos Ah yes, that could be nice for debugging the Uri. Thanks!

**Comment by isoos** [comment]
Pubished, thanks!

**Pull request merged**
